#!/usr/bin/env node

import { createHash } from 'node:crypto';
import { cp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const runtimeRoot = path.resolve(scriptDir, '..');
const projectRoot = path.resolve(runtimeRoot, '..');
const sourceDir = path.join(runtimeRoot, 'src');
const distDir = path.join(runtimeRoot, 'dist');
const generatedDir = path.join(runtimeRoot, 'generated');
const lock = JSON.parse(await readFile(path.join(runtimeRoot, 'vendor-lock.json'), 'utf8'));

for (const [sourceName, item] of Object.entries(lock.sources || {})) {
  const source = await readFile(path.join(projectRoot, sourceName), 'utf8');
  const vendored = await readFile(path.join(runtimeRoot, item.vendoredFile), 'utf8');
  if (sha256(source) !== item.sourceSha256) throw new Error(`${sourceName} がvendor後に変更されました。内容を確認して npm run vendor を実行してください。`);
  if (sha256(vendored) !== item.vendoredSha256) throw new Error(`${item.vendoredFile} がlockと一致しません。`);
}

const centralCoreSource = await readFile(path.join(projectRoot, 'VNext_Core.js'), 'utf8');
const clientCoreSource = await readFile(path.join(sourceDir, 'Client_Core.js'), 'utf8');
const centralHeaders = readSchema(centralCoreSource, 'VNEXT_CORE');
const clientHeaders = readSchema(clientCoreSource, 'VNEXT_CLIENT_CORE');
if (JSON.stringify(clientHeaders) !== JSON.stringify(centralHeaders)) {
  throw new Error('Client append-only headersがVNEXT_CORE.INTERNAL_SHEETSと一致しません。schema migrationを先に設計してください。');
}

await rm(distDir, { recursive: true, force: true });
await mkdir(distDir, { recursive: true });
await mkdir(generatedDir, { recursive: true });
for (const name of await readdir(sourceDir)) {
  if (!/\.(?:js|html|json)$/.test(name)) continue;
  await cp(path.join(sourceDir, name), path.join(distDir, name));
}

const verify = spawnSync(process.execPath, [path.join(scriptDir, 'verify.mjs'), '--dir', distDir], { encoding: 'utf8' });
if (verify.stdout) process.stdout.write(verify.stdout);
if (verify.stderr) process.stderr.write(verify.stderr);
if (verify.status !== 0) process.exit(verify.status || 1);

const files = [];
for (const name of (await readdir(distDir)).sort()) {
  const source = await readFile(path.join(distDir, name), 'utf8');
  const extension = path.extname(name);
  files.push({
    name: path.basename(name, extension),
    type: extension === '.html' ? 'HTML' : extension === '.json' ? 'JSON' : 'SERVER_JS',
    source
  });
}
const bundleHash = sha256(files.map((file) => `${file.name}\0${file.type}\0${file.source}`).join('\0'));
const bundle = { version: 'vnext-client-1.8.2', sha256: bundleHash, files };
await writeFile(path.join(generatedDir, 'client-runtime-bundle.json'), `${JSON.stringify(bundle, null, 2)}\n`, 'utf8');

const emitArg = readArg('--emit-gas-bundle');
if (emitArg) {
  const outputPath = path.resolve(process.cwd(), emitArg);
  const source = `/** GENERATED by client_runtime/scripts/build.mjs. Do not edit manually. */\n` +
    `var VNEXT_CLIENT_RUNTIME_BUNDLE_ = Object.freeze(${JSON.stringify(bundle)});\n`;
  await writeFile(outputPath, source, 'utf8');
  process.stdout.write(`Wrote GAS provisioning bundle: ${outputPath}\n`);
}
process.stdout.write(`Built client runtime sha256=${bundleHash}\n`);

function readArg(name) {
  const index = process.argv.indexOf(name);
  return index >= 0 ? process.argv[index + 1] : '';
}

function sha256(value) {
  return createHash('sha256').update(value, 'utf8').digest('hex');
}

function readSchema(source, globalName) {
  const context = vm.createContext({ console });
  new vm.Script(source, { filename: `${globalName}.js` }).runInContext(context);
  if (!context[globalName] || !context[globalName].INTERNAL_SHEETS) throw new Error(`${globalName}.INTERNAL_SHEETSがありません。`);
  return JSON.parse(JSON.stringify(context[globalName].INTERNAL_SHEETS));
}
