#!/usr/bin/env node

import { createHash } from 'node:crypto';
import { cp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const runtimeRoot = path.resolve(scriptDir, '..');
const sourceDir = path.join(runtimeRoot, 'src');
const distDir = path.join(runtimeRoot, 'dist');
const generatedDir = path.join(runtimeRoot, 'generated');

const verifySource = spawnSync(process.execPath, [path.join(scriptDir, 'verify.mjs'), '--dir', sourceDir], { encoding: 'utf8' });
if (verifySource.stdout) process.stdout.write(verifySource.stdout);
if (verifySource.stderr) process.stderr.write(verifySource.stderr);
if (verifySource.status !== 0) process.exit(verifySource.status || 1);

await rm(distDir, { recursive: true, force: true });
await mkdir(distDir, { recursive: true });
await mkdir(generatedDir, { recursive: true });
for (const name of (await readdir(sourceDir)).sort()) {
  if (/\.(?:js|html|json)$/.test(name)) await cp(path.join(sourceDir, name), path.join(distDir, name));
}

const verifyDist = spawnSync(process.execPath, [path.join(scriptDir, 'verify.mjs'), '--dir', distDir], { encoding: 'utf8' });
if (verifyDist.stdout) process.stdout.write(verifyDist.stdout);
if (verifyDist.stderr) process.stderr.write(verifyDist.stderr);
if (verifyDist.status !== 0) process.exit(verifyDist.status || 1);

const files = [];
for (const name of (await readdir(distDir)).sort()) {
  const source = await readFile(path.join(distDir, name), 'utf8');
  const extension = path.extname(name);
  files.push({
    name: path.basename(name, extension),
    type: extension === '.html' ? 'HTML' : extension === '.json' ? 'JSON' : 'SERVER_JS',
    source
  });
}
const sha256 = (value) => createHash('sha256').update(value, 'utf8').digest('hex');
const bundleHash = sha256(files.map((file) => `${file.name}\0${file.type}\0${file.source}`).join('\0'));
const bundle = { version: 'vnext-portal-1.7.3', sha256: bundleHash, files };
await writeFile(path.join(generatedDir, 'portal-runtime-bundle.json'), `${JSON.stringify(bundle, null, 2)}\n`, 'utf8');

const emitPath = readArg('--emit-gas-bundle');
if (emitPath) {
  const outputPath = path.resolve(process.cwd(), emitPath);
  const source = '/** GENERATED by portal_runtime/scripts/build.mjs. Do not edit manually. */\n' +
    `var VNEXT_PORTAL_RUNTIME_BUNDLE_ = Object.freeze(${JSON.stringify(bundle)});\n`;
  await writeFile(outputPath, source, 'utf8');
  process.stdout.write(`Wrote GAS portal provisioning bundle: ${outputPath}\n`);
}
process.stdout.write(`Built portal runtime sha256=${bundleHash}\n`);

function readArg(name) {
  const index = process.argv.indexOf(name);
  return index >= 0 ? process.argv[index + 1] : '';
}
